# Dockerfile for building image that contains software stack provisioned by Ansible.
#
# Version  1.0
#


# pull base image
FROM williamyeh/ansible:debian8-onbuild

MAINTAINER William Yeh <william.pjyeh@gmail.com>


#
# build phase
#

ENV PLAYBOOK test.yml
RUN ansible-playbook-wrapper -vvv --extra-vars "prometheus_mysqld_exporter_use_systemd=false"



#
# test phase
#

RUN echo "==> Removing PID files..."  && \
    rm -f /var/run/prometheus/*

RUN echo "===> Installing curl for testing purpose..."  && \
    DEBIAN_FRONTEND=noninteractive  \
    apt-get install -y -f curl


VOLUME ["/data"]
ENV    RESULT     /data/result-debian8

CMD  \
     service mysqld_exporter start &&  sleep 10  &&  \
     curl --retry 5 --retry-max-time 120  http://localhost:9104/metrics  > $RESULT
